-- =============================================
-- MAMINA Artesanías — Seed de productos de cerámica
-- Ejecutar en: Supabase Dashboard > SQL Editor
-- =============================================

insert into products (name, description, price, stock, image_url, category, delivery, accepts_mp, visible) values
('Tazón artesanal azul cobalto','Tazón de cerámica esmaltada a mano en azul cobalto. Perfecto para cereales, sopas o bowls. Capacidad aprox. 600ml. Cada pieza es única.',3500,5,'https://images.unsplash.com/photo-1565193566082-ef8bb680a8db?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Vasija decorativa terracotta','Vasija de terracota esmaltada con detalles naturales. Ideal para decoración o como florero. Altura 22cm, diámetro boca 8cm.',5200,3,'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Plato de servir esmaltado verde','Plato playo en esmalte verde salvia. Apto para lavavajillas y microondas. Diámetro 26cm.',4800,4,'https://images.unsplash.com/photo-1610701596061-2ecf227e9b66?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Jarra de cerámica con asa','Jarra con asa cómoda. Esmalte blanco roto con detalles terracota. Capacidad 1.2 litros.',4200,6,'https://images.unsplash.com/photo-1493219686142-5f91b68a1987?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Set 4 tazas espresso','Juego de 4 tazas espresso con esmaltes diferentes pero complementarios: azul, verde, blanco y ocre. Capacidad 80ml. En caja kraft.',6800,2,'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Bol pequeño para salsas','Bol multipropósito para salsas, aceite de oliva o condimentos. Esmalte crema con borde terracota. Diámetro 10cm.',1800,12,'https://images.unsplash.com/photo-1609557927087-f9cf8e88de18?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Taza grande café con leche','Taza amplia ideal para café con leche o té. Esmalte beige con manchas naturales del horneado. Capacidad 350ml.',2900,8,'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Fuente ovalada para mesa','Fuente para servir. Esmalte blanco con veteado azul. Medidas 35x22cm. Apta para horno 180°C, lavavajillas y microondas.',7500,2,'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80&auto=format&fit=crop','Cerámica','{"correo","retiro"}',true,true),
('Maceta colgante pintada a mano','Maceta de cerámica para colgar con cuerda de macramé incluida. Motivos florales pintados a mano. Diámetro 14cm. Con orificio de drenaje.',3200,0,'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80&auto=format&fit=crop','Decoración','{"correo","retiro"}',true,true),
('Candelabro cerámica blanca','Candelabro bajo con forma orgánica. Cerámica blanca mate. Para velas de hasta 4cm de diámetro o incienso en conos.',2800,7,'https://images.unsplash.com/photo-1482517967863-00e15c9b44be?w=800&q=80&auto=format&fit=crop','Decoración','{"correo","retiro"}',true,true),
('Florero cuello largo mostaza','Florero alto con cuello largo y estrecho. Esmalte mostaza. Altura 28cm. Perfecto para ramas secas o pampa grass.',4600,0,'https://images.unsplash.com/photo-1563241527-3f6bc84e93ef?w=800&q=80&auto=format&fit=crop','Decoración','{"correo","retiro"}',true,true),
('Portabudineras con tapa (set x2)','Set de 2 portabudineras con tapa. Esmalte crema interior, terracota exterior. Aptas para horno y microondas. 250ml c/u. Con caja de regalo.',5900,3,'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80&auto=format&fit=crop','Accesorios','{"correo","retiro"}',true,true);
